name: "infra"
services:
  redis:
    container_name: redis
    image: redis:5.0.6
    ports:
      - "6379:6379"
  rmq:
    container_name: rmq
    image: rabbitmq:3.7-management
    ports:
      - "15672:15672"
      - "5672:5672"
  mongo:
    container_name: mongo
    image: mongo:4.2.0
    volumes:
      - d:/mongo/data:/data/db
    ports:
      - "27017:27017"